/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.controle_contatos.views;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author gabriel
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        clienteMenu = new javax.swing.JMenu();
        itemListarCliente = new javax.swing.JMenuItem();
        itemInserirCliente = new javax.swing.JMenuItem();
        exitOption = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Clientes");

        clienteMenu.setText("Clientes");

        itemListarCliente.setText("Listar os clientes");
        clienteMenu.add(itemListarCliente);

        itemInserirCliente.setText("Inserir novo cliente");
        clienteMenu.add(itemInserirCliente);

        menuBar.add(clienteMenu);

        exitOption.setText("Sair");
        menuBar.add(exitOption);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu clienteMenu;
    private javax.swing.JMenu exitOption;
    private javax.swing.JMenuItem itemInserirCliente;
    private javax.swing.JMenuItem itemListarCliente;
    private javax.swing.JDesktopPane mainContainer;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    public JMenu getClienteMenu() {
        return clienteMenu;
    }

    public void setClienteMenu(JMenu clienteMenu) {
        this.clienteMenu = clienteMenu;
    }

    public JMenu getExitOption() {
        return exitOption;
    }

    public void setExitOption(JMenu exitOption) {
        this.exitOption = exitOption;
    }

    public JMenuItem getItemInserirCliente() {
        return itemInserirCliente;
    }

    public void setItemInserirCliente(JMenuItem itemInserirCliente) {
        this.itemInserirCliente = itemInserirCliente;
    }

    public JMenuItem getItemListarCliente() {
        return itemListarCliente;
    }

    public void setItemListarCliente(JMenuItem itemListarCliente) {
        this.itemListarCliente = itemListarCliente;
    }

    public JDesktopPane getMainContainer() {
        return mainContainer;
    }
    
}
